site:
  datasource_driver: com.mysql.cj.jdbc.Driver
  datasource_url: jdbc:mysql://8.140.205.210/luntan?useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
  datasource_username: ruangong
  datasource_password: 123456

# 想看mybatis执行的sql的时候，去掉下面这段的注释
#mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl